import "server-only";

import { createHash, randomBytes } from "node:crypto";

/**
 * Normalise a website integration token before hashing.
 *
 * Environment-variable dashboards can accidentally leave a token wrapped in
 * single/double quotes or with surrounding whitespace. Those characters are
 * not part of the credential generated by AgriCore.
 *
 * We deliberately do NOT alter anything inside the token.
 */
export function normaliseWebsiteIntegrationToken(value: string) {
  let token = value.trim();

  if (
    token.length >= 2 &&
    ((token.startsWith('"') && token.endsWith('"')) ||
      (token.startsWith("'") && token.endsWith("'")))
  ) {
    token = token.slice(1, -1).trim();
  }

  return token;
}

export function hashWebsiteIntegrationToken(token: string) {
  const normalised = normaliseWebsiteIntegrationToken(token);
  return createHash("sha256").update(normalised, "utf8").digest("hex");
}

export function websiteIntegrationKeyPrefix(token: string) {
  const normalised = normaliseWebsiteIntegrationToken(token);
  const match = /^(acwi_[0-9a-f]{8})_/i.exec(normalised);
  return match?.[1]?.toLowerCase() ?? "";
}

export function createWebsiteIntegrationToken() {
  const prefix = randomBytes(4).toString("hex");
  const secret = randomBytes(32).toString("base64url");
  const token = `acwi_${prefix}_${secret}`;

  return {
    token,
    keyPrefix: `acwi_${prefix}`,
    secretHash: hashWebsiteIntegrationToken(token),
  };
}
