import { requirePermission } from "@/lib/auth/require-permission";
import CompanyBrandingForm from "@/Components/settings/company-branding-form";
import FieldOperationsSettingsForm from "@/Components/settings/field-operations-settings";
import PaymentSettingsForm from "@/Components/settings/payment-settings-form";

export default async function CompanySettingsPage() {
  await requirePermission(["settings.manage"]);
  return (
    <main className="min-h-dvh w-full min-w-0">
      <div className="mx-auto max-w-5xl px-4 py-6 sm:px-6 lg:px-8 lg:py-8">
        <header className="mb-8">
          <p className="text-sm font-bold uppercase tracking-wide text-emerald-700">
            Settings
          </p>

          <h1 className="mt-1 text-3xl font-bold text-slate-900">
            Company branding
          </h1>

          <p className="mt-3 max-w-3xl text-base leading-7 text-slate-700">
            Configure the company information that appears on invoices,
            quotations, service reports, customer emails and other documents
            generated by AgriCore.
          </p>
        </header>

        <CompanyBrandingForm />
        <PaymentSettingsForm />
        <FieldOperationsSettingsForm />
      </div>
    </main>
  );
}