"use client";
import { FormEvent, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { Boxes, Network, ShieldCheck, Tractor } from "lucide-react";
import { useRegionalFormatters } from "@/lib/client/use-regional-formatters";

type Data = { settings?: any; machineListings?: any[]; partListings?: any[]; campaigns?: any[]; stockMachines?: any[]; stockItems?: any[]; publicMachineListings?: any[]; publicPartListings?: any[]; benchmarks?: any[]; error?: string };
export default function SalesNetworkPage() {
  const { money } = useRegionalFormatters(); const [data, setData] = useState<Data | null>(null); const [error, setError] = useState("");
  async function load() { setError(""); const response = await fetch("/api/sales/network", { cache: "no-store" }); const body = await response.json(); if (!response.ok) setError(body.error || "Unable to load network."); else setData(body); }
  useEffect(() => { void load(); }, []);
  async function post(payload: Record<string, unknown>) { const response = await fetch("/api/sales/network", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); const body = await response.json(); if (!response.ok) setError(body.error || "Unable to save."); else void load(); }
  async function saveSettings(patch: Record<string, boolean>) { const current = data?.settings ?? {}; await post({ action: "settings", network_opt_in: current.network_opt_in ?? false, marketplace_opt_in: current.marketplace_opt_in ?? false, benchmark_opt_in: current.benchmark_opt_in ?? false, ...patch }); }
  async function campaign(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); await post({ action: "campaign", ...Object.fromEntries(form.entries()) }); event.currentTarget.reset(); }
  const machinePublished = useMemo(() => new Map((data?.machineListings ?? []).map((row) => [row.stock_machine_id, Boolean(row.published)])), [data?.machineListings]);
  const partPublished = useMemo(() => new Map((data?.partListings ?? []).map((row) => [row.stock_item_id, Boolean(row.published)])), [data?.partListings]);
  if (error && !data) return <main className="p-8"><div className="rounded-3xl bg-rose-50 p-6 font-bold text-rose-800">{error}</div></main>;
  if (!data) return <main className="p-8 font-bold text-slate-500">Loading Enterprise Network…</main>;
  const settings = data.settings ?? {};
  return <main className="min-h-dvh bg-slate-50/60 p-4 sm:p-6 lg:p-8 dark:bg-slate-950"><div className="mx-auto max-w-[1500px] space-y-6"><header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[0.16em] text-emerald-700">Enterprise</p><h1 className="mt-1 text-3xl font-black text-slate-950 dark:text-white">Dealer & Marketplace Network</h1><p className="mt-2 max-w-3xl text-sm font-medium text-slate-500">Everything here is opt-in. Marketplace data is limited to records a participating company deliberately publishes; benchmark data is aggregated and contains no customer names.</p></div><Link href="/sales" className="rounded-xl border px-4 py-2 text-sm font-black">Back to Sales CRM</Link></header>{error ? <p className="rounded-xl bg-amber-50 px-4 py-3 text-sm font-bold text-amber-800">{error}</p> : null}<section className="grid gap-4 md:grid-cols-3"><Toggle icon={<Network/>} title="Dealer network" detail="Participate in dealer-to-dealer collaboration." value={Boolean(settings.network_opt_in)} onChange={(value) => void saveSettings({ network_opt_in: value })}/><Toggle icon={<Tractor/>} title="Marketplace publishing" detail="Allow only explicitly selected sales stock/parts to be visible to participating Enterprise companies." value={Boolean(settings.marketplace_opt_in)} onChange={(value) => void saveSettings({ marketplace_opt_in: value })}/><Toggle icon={<ShieldCheck/>} title="Anonymous benchmarks" detail="Opt in to aggregated machine/job statistics. Customer identity is never returned." value={Boolean(settings.benchmark_opt_in)} onChange={(value) => void saveSettings({ benchmark_opt_in: value })}/></section>
  <section className="grid gap-6 xl:grid-cols-2"><Box title="Publish machinery"><div className="space-y-2">{(data.stockMachines ?? []).map((item) => <div key={item.id} className="flex items-center justify-between gap-3 rounded-xl border p-3 dark:border-slate-700"><div><p className="font-black">{item.make} {item.model}</p><p className="text-xs font-semibold text-slate-500">{[item.stock_number,item.year,item.hours?`${item.hours} hrs`:null,money(Number(item.asking_price||0))].filter(Boolean).join(" · ")}</p></div><button disabled={!settings.marketplace_opt_in} onClick={() => void post({ action:"machine_listing", stock_machine_id:item.id, published:!machinePublished.get(item.id) })} className={`rounded-full px-3 py-1.5 text-xs font-black disabled:opacity-40 ${machinePublished.get(item.id)?"bg-emerald-100 text-emerald-800":"bg-slate-100 text-slate-600"}`}>{machinePublished.get(item.id)?"Published":"Publish"}</button></div>)}</div></Box><Box title="Publish parts"><div className="max-h-[420px] space-y-2 overflow-y-auto">{(data.stockItems ?? []).map((item) => <div key={item.id} className="flex items-center justify-between gap-3 rounded-xl border p-3 dark:border-slate-700"><div><p className="font-black">{item.part_number || item.description}</p><p className="text-xs font-semibold text-slate-500">{item.description} · {item.quantity_in_stock} in stock</p></div><button disabled={!settings.marketplace_opt_in} onClick={() => void post({ action:"part_listing", stock_item_id:item.id, published:!partPublished.get(item.id), quantity_available:Number(item.quantity_in_stock||0) })} className={`rounded-full px-3 py-1.5 text-xs font-black disabled:opacity-40 ${partPublished.get(item.id)?"bg-emerald-100 text-emerald-800":"bg-slate-100 text-slate-600"}`}>{partPublished.get(item.id)?"Published":"Publish"}</button></div>)}</div></Box></section>
  <section className="grid gap-6 xl:grid-cols-2"><Box title="Network machinery"><div className="space-y-2">{(data.publicMachineListings ?? []).map((row) => { const machine=Array.isArray(row.sales_stock_machines)?row.sales_stock_machines[0]:row.sales_stock_machines; return <div key={row.id} className="rounded-xl border p-3 dark:border-slate-700"><p className="font-black">{machine?.make} {machine?.model}</p><p className="text-xs font-semibold text-slate-500">{row.company_name} · {[machine?.year,machine?.hours?`${machine.hours} hrs`:null,money(Number(machine?.asking_price||0))].filter(Boolean).join(" · ")}</p></div>})}{!(data.publicMachineListings ?? []).length ? <Empty text="No participating dealers have published machinery yet."/>:null}</div></Box><Box title="Network parts"><div className="space-y-2">{(data.publicPartListings ?? []).map((row) => { const item=Array.isArray(row.stock_items)?row.stock_items[0]:row.stock_items; return <div key={row.id} className="rounded-xl border p-3 dark:border-slate-700"><p className="font-black">{item?.part_number || item?.description}</p><p className="text-xs font-semibold text-slate-500">{row.company_name} · {row.quantity_available} available · {money(Number(item?.unit_price||0))}</p></div>})}{!(data.publicPartListings ?? []).length ? <Empty text="No participating dealers have published parts yet."/>:null}</div></Box></section>
  <section className="grid gap-6 xl:grid-cols-2"><Box title="Dealer campaigns"><form onSubmit={campaign} className="grid gap-2 sm:grid-cols-2"><input name="title" required placeholder="Campaign title" className="rounded-xl border px-3 py-2 dark:bg-slate-950"/><input name="manufacturer" placeholder="Manufacturer" className="rounded-xl border px-3 py-2 dark:bg-slate-950"/><input name="reference" placeholder="Reference" className="rounded-xl border px-3 py-2 dark:bg-slate-950"/><select name="campaign_type" className="rounded-xl border px-3 py-2 dark:bg-slate-950"><option value="service_campaign">Service campaign</option><option value="recall">Recall</option><option value="warranty">Warranty</option></select><textarea name="description" placeholder="Description" className="sm:col-span-2 rounded-xl border px-3 py-2 dark:bg-slate-950"/><button className="sm:col-span-2 rounded-xl bg-emerald-700 px-4 py-2 text-sm font-black text-white">Add campaign</button></form><div className="mt-4 space-y-2">{(data.campaigns ?? []).map((row)=><div key={row.id} className="rounded-xl border p-3 dark:border-slate-700"><p className="font-black">{row.title}</p><p className="text-xs font-semibold text-slate-500">{[row.manufacturer,row.reference,row.campaign_type].filter(Boolean).join(" · ")}</p></div>)}</div></Box><Box title="Anonymous fleet benchmarks"><div className="space-y-2">{settings.benchmark_opt_in ? (data.benchmarks ?? []).map((row)=><div key={`${row.make}-${row.model}`} className="flex justify-between rounded-xl border p-3 dark:border-slate-700"><div><p className="font-black">{row.make} {row.model}</p><p className="text-xs font-semibold text-slate-500">Aggregated across opted-in companies</p></div><div className="text-right"><p className="font-black">{row.machines} machines</p><p className="text-xs font-semibold text-slate-500">{row.jobs} recorded jobs</p></div></div>) : <Empty text="Opt in to anonymous benchmarks to see aggregated fleet statistics."/>}</div></Box></section>
  </div></main>;
}
function Toggle({ icon,title,detail,value,onChange }: { icon: React.ReactNode; title:string;detail:string;value:boolean;onChange:(value:boolean)=>void }) { return <div className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="text-emerald-700">{icon}</div><p className="mt-4 font-black text-slate-950 dark:text-white">{title}</p><p className="mt-1 text-sm font-medium leading-6 text-slate-500">{detail}</p><button onClick={() => onChange(!value)} className={`mt-4 rounded-full px-4 py-2 text-xs font-black ${value ? "bg-emerald-100 text-emerald-800" : "bg-slate-100 text-slate-600"}`}>{value ? "Opted in" : "Opted out"}</button></div> }
function Box({ title,children }: { title:string;children:React.ReactNode }) { return <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><h2 className="mb-4 text-lg font-black text-slate-950 dark:text-white">{title}</h2>{children}</section> }
function Empty({text}:{text:string}){return <div className="rounded-xl border border-dashed p-5 text-center text-sm font-semibold text-slate-500">{text}</div>}
