"use client";
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";

type BankAccount={id:string;finance_account_id:string;name:string;bank_name:string|null;account_reference:string|null;currency_code:string;opening_balance:number|string;is_default:boolean;active:boolean};
type FinanceAccount={id:string;code:string;name:string;account_type:string;system_key:string|null};
type Transaction={id:string;bank_account_id:string;transaction_date:string;transaction_type:string|null;description:string|null;reference:string|null;amount:number|string;running_balance:number|string|null;external_id:string|null;reconciliation_status:string;import_batch:string|null};
type SupplierPayment={id:string;supplier_id:string;payment_date:string;amount:number|string;reference:string|null;bank_account_id:string|null;status:string;stock_suppliers:{name:string}|null};
type Journal={id:string;journal_date:string;reference:string|null;description:string|null;source_type:string|null;source_id:string|null;source_action:string;status:string;finance_journal_lines:Array<{account_id:string;debit:number|string;credit:number|string;finance_accounts:{account_type:string;system_key:string|null}}>};
type Payload={bankAccounts:BankAccount[];financeAccounts:FinanceAccount[];transactions:Transaction[];supplierPayments:SupplierPayment[];journals:Journal[]};
const num=(v:unknown)=>Number(v??0)||0; const gbp=(v:unknown)=>new Intl.NumberFormat("en-GB",{style:"currency",currency:"GBP"}).format(num(v));
export default function BankReconciliationClient(){
 const [data,setData]=useState<Payload|null>(null);const [bankId,setBankId]=useState("");const [error,setError]=useState("");const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);const [csv,setCsv]=useState("");const [selected,setSelected]=useState<Transaction|null>(null);const [target,setTarget]=useState("");const [matchAmount,setMatchAmount]=useState("");const [bankForm,setBankForm]=useState({name:"",bank_name:"",account_reference:"",finance_account_id:"",opening_balance:"0"});
 const load=useCallback(async()=>{setError("");const query=bankId?`?bank_account_id=${encodeURIComponent(bankId)}`:"";const r=await fetch(`/api/finance/bank${query}`,{cache:"no-store"});const b=await r.json();if(!r.ok)throw new Error(b.error||"Unable to load bank reconciliation.");setData(b);if(!bankId&&b.bankAccounts?.length)setBankId(b.bankAccounts[0].id);},[bankId]);
 useEffect(()=>{load().catch(e=>setError(e.message));},[load]);
 const transactions=useMemo(()=>data?.transactions??[],[data]);const unmatched=transactions.filter(t=>t.reconciliation_status==="unmatched"||t.reconciliation_status==="part_matched");const matched=transactions.filter(t=>t.reconciliation_status==="matched");
 async function createBank(e:FormEvent){e.preventDefault();setBusy(true);setError("");try{const r=await fetch("/api/finance/bank",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(bankForm)});const b=await r.json();if(!r.ok)throw new Error(b.error||"Unable to create bank account.");setBankForm({name:"",bank_name:"",account_reference:"",finance_account_id:"",opening_balance:"0"});setMessage("Bank account added.");await load();}catch(e){setError(e instanceof Error?e.message:"Unable to create bank account.");}finally{setBusy(false);}}
 async function importCsv(e:FormEvent){e.preventDefault();if(!bankId)return;setBusy(true);setError("");setMessage("");try{const r=await fetch("/api/finance/bank/import",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({bank_account_id:bankId,csv})});const b=await r.json();if(!r.ok)throw new Error(b.error||"Unable to import bank CSV.");setMessage(`Imported ${b.imported} transaction${b.imported===1?"":"s"}${b.rejected?` · ${b.rejected} rejected`:""}.`);setCsv("");await load();}catch(e){setError(e instanceof Error?e.message:"Unable to import bank CSV.");}finally{setBusy(false);}}
 function openMatch(t:Transaction){setSelected(t);setMatchAmount(Math.abs(num(t.amount)).toFixed(2));setTarget("");}
 const candidates=useMemo(()=>{if(!selected||!data)return [] as Array<{value:string;label:string}>;const amount=Math.abs(num(selected.amount));const date=Date.parse(selected.transaction_date);const out:Array<{value:string;label:string}>=[];if(num(selected.amount)<0){for(const p of data.supplierPayments){if(p.bank_account_id&&p.bank_account_id!==selected.bank_account_id)continue;const diff=Math.abs(Date.parse(p.payment_date)-date)/86400000;if(Math.abs(num(p.amount)-amount)<=0.01&&diff<=7)out.push({value:`payment:${p.id}`,label:`Supplier payment · ${p.stock_suppliers?.name??"Supplier"} · ${p.payment_date} · ${gbp(p.amount)}${p.reference?` · ${p.reference}`:""}`});}}
 for(const j of data.journals){const bankMovement=j.finance_journal_lines.reduce((sum,line)=>sum+(line.finance_accounts?.system_key==="bank"?num(line.debit)-num(line.credit):0),0);const diff=Math.abs(Date.parse(j.journal_date)-date)/86400000;if(Math.abs(Math.abs(bankMovement)-amount)<=0.01&&diff<=7)out.push({value:`journal:${j.id}`,label:`Journal · ${j.journal_date} · ${j.reference??j.description??j.source_action} · ${gbp(Math.abs(bankMovement))}`});}return out.slice(0,30);},[selected,data]);
 async function reconcile(e:FormEvent){e.preventDefault();if(!selected||!target)return;setBusy(true);setError("");try{const [kind,id]=target.split(":");const r=await fetch("/api/finance/bank/reconcile",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({bank_transaction_id:selected.id,matched_amount:Number(matchAmount),journal_id:kind==="journal"?id:null,supplier_payment_id:kind==="payment"?id:null})});const b=await r.json();if(!r.ok)throw new Error(b.error||"Unable to reconcile transaction.");setSelected(null);setMessage("Bank transaction matched.");await load();}catch(e){setError(e instanceof Error?e.message:"Unable to reconcile transaction.");}finally{setBusy(false);}}
 async function ignore(id:string){setBusy(true);try{const r=await fetch("/api/finance/bank/reconcile",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,status:"ignored"})});const b=await r.json();if(!r.ok)throw new Error(b.error||"Unable to ignore transaction.");await load();}catch(e){setError(e instanceof Error?e.message:"Unable to ignore transaction.");}finally{setBusy(false);}}
 return <main className="w-full space-y-6 px-5 py-5 lg:px-7"><div><p className="text-sm font-semibold text-emerald-700">Atlas Finance</p><h1 className="mt-1 text-3xl font-black tracking-tight text-slate-950 dark:text-white">Bank reconciliation</h1><p className="mt-2 text-sm font-medium text-slate-500 dark:text-slate-400">Import bank statements and match them against finance activity without creating duplicate ledger entries.</p></div>{error&&<p className="rounded-xl bg-red-50 p-3 text-sm font-semibold text-red-700">{error}</p>}{message&&<p className="rounded-xl bg-emerald-50 p-3 text-sm font-semibold text-emerald-800">{message}</p>}
 <section className="grid gap-4 sm:grid-cols-3"><Stat label="Imported" value={String(transactions.length)}/><Stat label="Unmatched" value={String(unmatched.length)}/><Stat label="Matched" value={String(matched.length)}/></section>
 <div className="grid gap-6 xl:grid-cols-2"><Panel title="Bank accounts" description="Link each real bank account to an AgriCore asset account."><form onSubmit={createBank} className="grid gap-3 sm:grid-cols-2"><Field label="Display name"><input className="input" required value={bankForm.name} onChange={e=>setBankForm({...bankForm,name:e.target.value})}/></Field><Field label="Bank"><input className="input" value={bankForm.bank_name} onChange={e=>setBankForm({...bankForm,bank_name:e.target.value})}/></Field><Field label="Account reference"><input className="input" value={bankForm.account_reference} onChange={e=>setBankForm({...bankForm,account_reference:e.target.value})}/></Field><Field label="Finance account"><select className="input" required value={bankForm.finance_account_id} onChange={e=>setBankForm({...bankForm,finance_account_id:e.target.value})}><option value="">Select asset account…</option>{data?.financeAccounts.map(a=><option key={a.id} value={a.id}>{a.code} · {a.name}</option>)}</select></Field><button disabled={busy} className="rounded-xl bg-[#103D2E] px-4 py-3 text-sm font-bold text-white sm:col-span-2">Add bank account</button></form><div className="mt-5 space-y-2">{data?.bankAccounts.map(b=><div key={b.id} className="rounded-xl border border-slate-200 p-3 text-sm dark:border-slate-800"><p className="font-black text-slate-950 dark:text-white">{b.name}</p><p className="text-slate-500">{b.bank_name??"Bank"}{b.account_reference?` · ${b.account_reference}`:""}</p></div>)}</div></Panel>
 <Panel title="Import statement" description="CSV supports Date + Amount, or Date + Debit/Credit. UK DD/MM/YYYY and ISO dates are accepted."><form onSubmit={importCsv} className="space-y-3"><Field label="Bank account"><select className="input" required value={bankId} onChange={e=>setBankId(e.target.value)}><option value="">Select bank account…</option>{data?.bankAccounts.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></Field><Field label="CSV"><textarea rows={8} className="input font-mono text-xs" value={csv} onChange={e=>setCsv(e.target.value)} placeholder={'Date,Description,Reference,Amount,Balance\n12/08/2026,Customer receipt,INV-001,240.00,5400.00'}/></Field><label className="inline-flex cursor-pointer rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-bold dark:border-slate-700">Load CSV file<input type="file" accept=".csv,text/csv" className="hidden" onChange={async e=>{const f=e.target.files?.[0];if(f)setCsv(await f.text());}}/></label><button disabled={busy||!bankId||!csv.trim()} className="ml-2 rounded-xl bg-[#103D2E] px-4 py-2.5 text-sm font-bold text-white disabled:opacity-50">Import</button></form></Panel></div>
 <Panel title="Transactions" description="Positive amounts are money in; negative amounts are money out."><div className="overflow-x-auto"><table className="min-w-[900px] w-full text-left text-sm"><thead><tr>{["Date","Description","Reference","Amount","Status","Actions"].map(h=><th key={h} className="border-b border-slate-200 px-3 py-2 text-xs font-black uppercase tracking-wide text-slate-500 dark:border-slate-800">{h}</th>)}</tr></thead><tbody>{transactions.map(t=><tr key={t.id}><td className="cell">{t.transaction_date}</td><td className="cell font-bold">{t.description??"—"}</td><td className="cell">{t.reference??"—"}</td><td className={`cell font-black ${num(t.amount)>=0?"text-emerald-700":"text-slate-950 dark:text-white"}`}>{gbp(t.amount)}</td><td className="cell"><Status value={t.reconciliation_status}/></td><td className="cell"><div className="flex gap-2">{["unmatched","part_matched"].includes(t.reconciliation_status)&&<button onClick={()=>openMatch(t)} className="rounded-lg bg-[#103D2E] px-3 py-2 text-xs font-bold text-white">Match</button>}{t.reconciliation_status==="unmatched"&&<button onClick={()=>void ignore(t.id)} className="rounded-lg border border-slate-200 px-3 py-2 text-xs font-bold dark:border-slate-700">Ignore</button>}</div></td></tr>)}{!transactions.length&&<tr><td colSpan={6} className="px-3 py-10 text-center font-semibold text-slate-500">No bank transactions imported.</td></tr>}</tbody></table></div></Panel>
 {selected&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/50 p-4"><div className="w-full max-w-2xl rounded-3xl bg-white p-6 shadow-2xl dark:bg-slate-950"><div className="flex justify-between gap-3"><div><p className="text-sm font-semibold text-emerald-700">Match transaction</p><h2 className="mt-1 text-2xl font-black dark:text-white">{gbp(selected.amount)}</h2><p className="text-sm text-slate-500">{selected.transaction_date} · {selected.description??selected.reference??"Bank transaction"}</p></div><button onClick={()=>setSelected(null)} className="rounded-xl border border-slate-200 px-3 py-2 text-sm font-bold dark:border-slate-700">Close</button></div><form onSubmit={reconcile} className="mt-5 space-y-4"><Field label="Suggested finance activity"><select required className="input" value={target} onChange={e=>setTarget(e.target.value)}><option value="">Select match…</option>{candidates.map(c=><option key={c.value} value={c.value}>{c.label}</option>)}</select></Field>{!candidates.length&&<p className="rounded-xl bg-amber-50 p-3 text-sm font-semibold text-amber-800">No exact amount/date candidates were found. Post or record the finance activity first, then return to reconciliation.</p>}<Field label="Matched amount"><input required min="0.01" step="0.01" type="number" className="input" value={matchAmount} onChange={e=>setMatchAmount(e.target.value)}/></Field><button disabled={busy||!target} className="w-full rounded-xl bg-[#103D2E] px-4 py-3 text-sm font-bold text-white disabled:opacity-50">Confirm match</button></form></div></div>}
 <style jsx global>{`.input{width:100%;border-radius:.75rem;border:1px solid rgb(226 232 240);background:white;padding:.7rem .8rem;font-size:.875rem;color:rgb(15 23 42);outline:none}.dark .input{border-color:rgb(51 65 85);background:rgb(15 23 42);color:rgb(241 245 249)}.cell{border-bottom:1px solid rgb(241 245 249);padding:.75rem;color:rgb(51 65 85)}.dark .cell{border-color:rgb(30 41 59);color:rgb(226 232 240)}`}</style></main>;
}
function Panel({title,description,children}:{title:string;description?:string;children:React.ReactNode}){return <section className="rounded-2xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-950"><h2 className="text-lg font-black text-slate-950 dark:text-white">{title}</h2>{description&&<p className="mt-1 text-sm font-medium text-slate-500">{description}</p>}<div className="mt-5">{children}</div></section>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block"><span className="mb-1.5 block text-xs font-black uppercase tracking-wide text-slate-500">{label}</span>{children}</label>}
function Stat({label,value}:{label:string;value:string}){return <div className="rounded-2xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-950"><p className="text-xs font-black uppercase tracking-wide text-slate-500">{label}</p><p className="mt-2 text-2xl font-black text-slate-950 dark:text-white">{value}</p></div>}
function Status({value}:{value:string}){const cls=value==="matched"?"bg-emerald-100 text-emerald-800":value==="part_matched"?"bg-amber-100 text-amber-800":value==="ignored"?"bg-slate-200 text-slate-700":"bg-blue-100 text-blue-800";return <span className={`inline-flex rounded-full px-2.5 py-1 text-xs font-black ${cls}`}>{value.replaceAll("_"," ")}</span>}
