"use client";
import { FormEvent,useEffect,useState } from "react";
import Link from "next/link";
type Profile={public_slug:string;opted_in:boolean;approval_status:string;display_name:string;description:string|null;town_city:string|null;postcode:string|null;service_radius_miles:number;emergency_callouts:boolean;phone:string|null;email:string|null;website:string|null;brands:string[];services:string[];business_verification:string;identity_verification:string;insurance_verification:string;insurance_expiry:string|null;application_notes:string|null;suspension_reason:string|null};
type RequestRow={id:string;customer_name:string;customer_email:string|null;customer_phone:string|null;location:string;machine_description:string|null;service_required:string;urgency:string;preferred_contact:string;message:string|null;status:string;created_at:string};
export default function NetworkProviderPage(){
 const[profile,setProfile]=useState<Profile|null>(null),[requests,setRequests]=useState<RequestRow[]>([]),[companyName,setCompanyName]=useState(""),[error,setError]=useState(""),[saving,setSaving]=useState(false);
 const[form,setForm]=useState<any>({display_name:"",description:"",town_city:"",postcode:"",service_radius_miles:30,emergency_callouts:false,phone:"",email:"",website:"",brands:"",services:"",application_notes:"",opted_in:false});
 async function load(){setError("");const r=await fetch("/api/network/provider",{cache:"no-store"});const b=await r.json();if(!r.ok){setError(b.error||"Unable to load Network profile.");return;}setProfile(b.profile);setRequests(b.requests??[]);setCompanyName(b.company?.company_name??"");const p=b.profile;setForm({display_name:p?.display_name??b.company?.company_name??"",description:p?.description??"",town_city:p?.town_city??"",postcode:p?.postcode??"",service_radius_miles:p?.service_radius_miles??30,emergency_callouts:Boolean(p?.emergency_callouts),phone:p?.phone??"",email:p?.email??"",website:p?.website??"",brands:(p?.brands??[]).join(", "),services:(p?.services??[]).join(", "),application_notes:p?.application_notes??"",opted_in:Boolean(p?.opted_in)});}
 useEffect(()=>{void load()},[]);
 async function save(action="save"){setSaving(true);setError("");try{const r=await fetch("/api/network/provider",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,...form,brands:form.brands.split(",").map((x:string)=>x.trim()).filter(Boolean),services:form.services.split(",").map((x:string)=>x.trim()).filter(Boolean)})});const b=await r.json();if(!r.ok)throw new Error(b.error||"Unable to save.");await load();}catch(e){setError(e instanceof Error?e.message:"Unable to save.");}finally{setSaving(false)}}
 const input="mt-1 w-full rounded-xl border border-slate-200 bg-white px-3 py-3 dark:border-slate-700 dark:bg-slate-950";
 return <main className="min-h-dvh bg-slate-50/60 p-4 sm:p-6 lg:p-8 dark:bg-slate-950"><div className="mx-auto max-w-6xl space-y-6">
  <header><p className="text-xs font-black uppercase tracking-[.16em] text-emerald-700">AgriCore Network</p><h1 className="mt-1 text-3xl font-black">Provider profile & requests</h1><p className="mt-2 max-w-3xl text-sm font-medium text-slate-500">Apply to appear in the public AgriCore mechanic marketplace. Subscription access and Network approval are separate.</p></header>
  {error?<div className="rounded-xl bg-red-50 px-4 py-3 text-sm font-bold text-red-700">{error}</div>:null}
  <section className="rounded-3xl border bg-white p-6 dark:border-slate-800 dark:bg-slate-900">
   <div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-black">{companyName||"Provider profile"}</h2><p className="mt-1 text-sm text-slate-500">Status: <b className="capitalize">{profile?.approval_status??"Not submitted"}</b></p></div>{profile?.approval_status==="approved"?<Link href={`/network/${profile.public_slug}`} target="_blank" className="rounded-xl border px-4 py-2 text-sm font-black">View public profile</Link>:null}</div>
   {profile?.suspension_reason?<p className="mt-4 rounded-xl bg-red-50 p-3 text-sm font-bold text-red-700">{profile.suspension_reason}</p>:null}
   <div className="mt-6 grid gap-4 md:grid-cols-2">
    <label className="text-sm font-bold">Public business name<input className={input} value={form.display_name} onChange={e=>setForm({...form,display_name:e.target.value})}/></label>
    <label className="text-sm font-bold">Town / city<input className={input} value={form.town_city} onChange={e=>setForm({...form,town_city:e.target.value})}/></label>
    <label className="text-sm font-bold">Postcode<input className={input} value={form.postcode} onChange={e=>setForm({...form,postcode:e.target.value})}/></label>
    <label className="text-sm font-bold">Service radius (miles)<input type="number" min="1" max="500" className={input} value={form.service_radius_miles} onChange={e=>setForm({...form,service_radius_miles:Number(e.target.value)})}/></label>
    <label className="text-sm font-bold">Phone<input className={input} value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label>
    <label className="text-sm font-bold">Email<input type="email" className={input} value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label>
    <label className="md:col-span-2 text-sm font-bold">Website<input className={input} value={form.website} onChange={e=>setForm({...form,website:e.target.value})}/></label>
    <label className="md:col-span-2 text-sm font-bold">About your business<textarea rows={4} className={input} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label>
    <label className="md:col-span-2 text-sm font-bold">Services <span className="font-medium text-slate-500">(comma separated)</span><input className={input} value={form.services} onChange={e=>setForm({...form,services:e.target.value})} placeholder="Breakdowns, diagnostics, servicing, hydraulics"/></label>
    <label className="md:col-span-2 text-sm font-bold">Brands <span className="font-medium text-slate-500">(comma separated)</span><input className={input} value={form.brands} onChange={e=>setForm({...form,brands:e.target.value})} placeholder="New Holland, Case IH, JCB"/></label>
    <label className="md:col-span-2 text-sm font-bold">Verification notes<textarea rows={3} className={input} value={form.application_notes} onChange={e=>setForm({...form,application_notes:e.target.value})} placeholder="Business registration, insurance details, experience, relevant qualifications or links."/></label>
   </div>
   <div className="mt-5 flex flex-wrap gap-4"><label className="flex items-center gap-2 text-sm font-bold"><input type="checkbox" checked={form.emergency_callouts} onChange={e=>setForm({...form,emergency_callouts:e.target.checked})}/>Accept emergency/breakdown callouts</label><label className="flex items-center gap-2 text-sm font-bold"><input type="checkbox" checked={form.opted_in} onChange={e=>setForm({...form,opted_in:e.target.checked})}/>List publicly once approved</label></div>
   <div className="mt-6 flex flex-wrap gap-3"><button disabled={saving} onClick={()=>void save("save")} className="rounded-xl border px-5 py-3 text-sm font-black">Save draft</button><button disabled={saving} onClick={()=>void save("submit")} className="rounded-xl bg-emerald-700 px-5 py-3 text-sm font-black text-white">Submit for Network approval</button></div>
   {profile?<div className="mt-6 grid gap-3 sm:grid-cols-3">{[["Business",profile.business_verification],["Identity",profile.identity_verification],["Insurance",profile.insurance_verification]].map(([a,b])=><div key={a} className="rounded-xl bg-slate-50 p-3 text-sm dark:bg-slate-950"><b>{a}</b><span className="ml-2 capitalize text-slate-500">{b.replace("_"," ")}</span></div>)}</div>:null}
  </section>
  <section className="rounded-3xl border bg-white p-6 dark:border-slate-800 dark:bg-slate-900"><h2 className="text-xl font-black">Direct Network requests</h2><p className="mt-1 text-sm text-slate-500">Requests submitted specifically to your approved public profile. These are separate from your existing website enquiries.</p><div className="mt-5 space-y-3">{requests.length?requests.map(r=><article key={r.id} className="rounded-2xl border p-4"><div className="flex flex-wrap justify-between gap-3"><div><p className="font-black">{r.customer_name} · {r.service_required}</p><p className="mt-1 text-sm text-slate-500">{r.location} · {r.urgency} · {new Date(r.created_at).toLocaleString("en-GB")}</p></div><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-black capitalize">{r.status}</span></div><p className="mt-3 text-sm">{r.machine_description||"No machine details"}</p>{r.message?<p className="mt-2 text-sm text-slate-600">{r.message}</p>:null}<p className="mt-3 text-sm font-semibold">{[r.customer_phone,r.customer_email].filter(Boolean).join(" · ")}</p></article>):<p className="text-sm text-slate-500">No Network requests yet.</p>}</div></section>
 </div></main>
}