import { NextRequest, NextResponse } from "next/server";
import { getAuthenticatedUserContext } from "@/lib/auth/require-permission";
import { createSupabaseAdmin } from "@/lib/payments/supabase-admin";
import { canManageCompany } from "@/lib/platform/core";
import { financeBranchIds } from "@/lib/branches/finance";
export const dynamic = "force-dynamic";
const n=(v:unknown)=>Number(v??0)||0; const m=(v:number)=>Math.round((v+Number.EPSILON)*100)/100;
function allowed(auth: NonNullable<Awaited<ReturnType<typeof getAuthenticatedUserContext>>>) { return canManageCompany(auth)||auth.permissions.includes("settings.manage")||auth.permissions.includes("finance.reports"); }
type Account={id:string;code:string;name:string;account_type:"asset"|"liability"|"equity"|"income"|"expense";normal_balance:"debit"|"credit";system_key:string|null};
type Line={debit:number|string|null;credit:number|string|null;account_id:string;finance_accounts:Account;finance_journals:{journal_date:string;status:string}};
export async function GET(request:NextRequest){const auth=await getAuthenticatedUserContext();if(!auth)return NextResponse.json({error:"Authentication required."},{status:401});if(!allowed(auth))return NextResponse.json({error:"Finance reporting permission is required."},{status:403});const today=new Date().toISOString().slice(0,10);const from=request.nextUrl.searchParams.get("from")||`${new Date().getUTCFullYear()}-01-01`;const to=request.nextUrl.searchParams.get("to")||today;const admin=createSupabaseAdmin();const branchIds=financeBranchIds(auth);const [periodResult,allResult,purchases]=await Promise.all([
 admin.from("finance_journal_lines").select("debit,credit,account_id,finance_accounts!inner(id,code,name,account_type,normal_balance,system_key),finance_journals!inner(journal_date,status)").eq("company_id",auth.companyId).in("finance_journals.branch_id",branchIds).eq("finance_journals.status","posted").gte("finance_journals.journal_date",from).lte("finance_journals.journal_date",to),
 admin.from("finance_journal_lines").select("debit,credit,account_id,finance_accounts!inner(id,code,name,account_type,normal_balance,system_key),finance_journals!inner(journal_date,status)").eq("company_id",auth.companyId).in("finance_journals.branch_id",branchIds).eq("finance_journals.status","posted").lte("finance_journals.journal_date",to),
 admin.from("finance_purchase_invoices").select("id,status,total,amount_paid,due_date,invoice_date,invoice_number,stock_suppliers(name)").eq("company_id",auth.companyId).in("branch_id",branchIds).in("status",["posted","part_paid"])
]);const error=periodResult.error||allResult.error||purchases.error;if(error)return NextResponse.json({error:error.message},{status:500});
 const aggregate=(rows:unknown[])=>{const map=new Map<string,{id:string;code:string;name:string;type:string;normal:string;systemKey:string|null;debit:number;credit:number}>();for(const raw of rows){const row=raw as Line;const a=row.finance_accounts;const current=map.get(a.id)||{id:a.id,code:a.code,name:a.name,type:a.account_type,normal:a.normal_balance,systemKey:a.system_key,debit:0,credit:0};current.debit+=n(row.debit);current.credit+=n(row.credit);map.set(a.id,current);}return [...map.values()].map(x=>({...x,debit:m(x.debit),credit:m(x.credit),balance:m(x.normal==="credit"?x.credit-x.debit:x.debit-x.credit)}));};
 const period=aggregate(periodResult.data??[]);const cumulative=aggregate(allResult.data??[]);const income=period.filter(x=>x.type==="income").sort((a,b)=>a.code.localeCompare(b.code));const expenses=period.filter(x=>x.type==="expense").sort((a,b)=>a.code.localeCompare(b.code));const revenue=m(income.reduce((s,x)=>s+x.balance,0));const expenseTotal=m(expenses.reduce((s,x)=>s+x.balance,0));const assets=cumulative.filter(x=>x.type==="asset").sort((a,b)=>a.code.localeCompare(b.code));const liabilities=cumulative.filter(x=>x.type==="liability").sort((a,b)=>a.code.localeCompare(b.code));const equity=cumulative.filter(x=>x.type==="equity").sort((a,b)=>a.code.localeCompare(b.code));const currentProfit=m(revenue-expenseTotal);const assetTotal=m(assets.reduce((s,x)=>s+x.balance,0));const liabilityTotal=m(liabilities.reduce((s,x)=>s+x.balance,0));const equityTotal=m(equity.reduce((s,x)=>s+x.balance,0)+currentProfit);const aged=(purchases.data??[]).map(p=>({id:p.id,invoiceNumber:p.invoice_number,supplier:(p.stock_suppliers as unknown as {name:string}|null)?.name??"Supplier",dueDate:p.due_date,invoiceDate:p.invoice_date,outstanding:m(Math.max(0,n(p.total)-n(p.amount_paid)))})).filter(p=>p.outstanding>0.009);const buckets={current:0,days30:0,days60:0,days90:0,older:0};for(const p of aged){if(!p.dueDate){buckets.current+=p.outstanding;continue;}const days=Math.floor((Date.parse(to)-Date.parse(p.dueDate))/86400000);if(days<=0)buckets.current+=p.outstanding;else if(days<=30)buckets.days30+=p.outstanding;else if(days<=60)buckets.days60+=p.outstanding;else if(days<=90)buckets.days90+=p.outstanding;else buckets.older+=p.outstanding;}for(const key of Object.keys(buckets) as Array<keyof typeof buckets>)buckets[key]=m(buckets[key]);
 const bank=cumulative.filter(x=>x.systemKey==="bank").reduce((s,x)=>s+x.balance,0);const receivables=cumulative.filter(x=>x.systemKey==="accounts_receivable").reduce((s,x)=>s+x.balance,0);const payables=cumulative.filter(x=>x.systemKey==="accounts_payable").reduce((s,x)=>s+x.balance,0);
 return NextResponse.json({from,to,profitLoss:{income,expenses,revenue,expenseTotal,netProfit:currentProfit},balanceSheet:{assets,liabilities,equity,assetTotal,liabilityTotal,equityTotal,balanceCheck:m(assetTotal-liabilityTotal-equityTotal)},cashSummary:{bank:m(bank),receivables:m(receivables),payables:m(payables)},agedCreditors:{buckets,total:m(aged.reduce((s,x)=>s+x.outstanding,0)),invoices:aged.sort((a,b)=>String(a.dueDate??a.invoiceDate).localeCompare(String(b.dueDate??b.invoiceDate)))}},{headers:{"Cache-Control":"no-store"}});}
