"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";

type Branch = { id:string; code:string; name:string; branch_type:string; is_head_office:boolean; address:string|null; phone:string|null; email:string|null; manager_user_id:string|null; active:boolean };
type Member = { userId:string; fullName:string; role:string; homeBranchId:string|null; operationsScope:string; financeScope:string; branchIds:string[] };
type Payload = { branches:Branch[]; members:Member[]; error?:string };

const opsOptions = [
  ["own_jobs","Own assigned jobs"],
  ["branch","Home depot"],
  ["selected","Selected depots"],
  ["company","Whole company"],
] as const;
const financeOptions = [
  ["none","No financial scope"],
  ["branch","Home depot"],
  ["selected","Selected depots"],
  ["company","Whole company"],
] as const;

export default function BranchManagementClient(){
  const [branches,setBranches]=useState<Branch[]>([]);
  const [members,setMembers]=useState<Member[]>([]);
  const [loading,setLoading]=useState(true);
  const [saving,setSaving]=useState("");
  const [error,setError]=useState("");
  const [notice,setNotice]=useState("");
  const [form,setForm]=useState({name:"",code:"",branchType:"depot",address:"",phone:"",email:""});

  const load=useCallback(async()=>{setLoading(true);setError("");try{const r=await fetch("/api/settings/branches",{cache:"no-store"});const b=(await r.json()) as Payload;if(!r.ok)throw new Error(b.error||"Unable to load depots.");setBranches(b.branches||[]);setMembers(b.members||[]);}catch(e){setError(e instanceof Error?e.message:"Unable to load depots.");}finally{setLoading(false);}},[]);
  useEffect(()=>{void load();},[load]);

  async function createBranch(e:FormEvent){e.preventDefault();setSaving("new");setError("");setNotice("");try{const r=await fetch("/api/settings/branches",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const b=await r.json();if(!r.ok)throw new Error(b.error||"Unable to create depot.");setForm({name:"",code:"",branchType:"depot",address:"",phone:"",email:""});setNotice("Depot created.");await load();}catch(e){setError(e instanceof Error?e.message:"Unable to create depot.");}finally{setSaving("");}}
  async function saveBranchManager(branchId:string,managerUserId:string){setSaving(`branch-${branchId}`);setError("");setNotice("");try{const r=await fetch("/api/settings/branches",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({branchId,managerUserId})});const b=await r.json();if(!r.ok)throw new Error(b.error||"Unable to save depot manager.");setBranches(current=>current.map(branch=>branch.id===branchId?{...branch,manager_user_id:b.branch?.manager_user_id??null}:branch));setNotice("Depot manager saved.");}catch(e){setError(e instanceof Error?e.message:"Unable to save depot manager.");}finally{setSaving("");}}

  function updateMember(userId:string,patch:Partial<Member>){setMembers(current=>current.map(member=>member.userId===userId?{...member,...patch}:member));}
  async function saveMember(member:Member){setSaving(member.userId);setError("");setNotice("");try{const r=await fetch("/api/settings/branches/access",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(member)});const b=await r.json();if(!r.ok)throw new Error(b.error||"Unable to save depot access.");setNotice(`${member.fullName}'s depot access was saved.`);}catch(e){setError(e instanceof Error?e.message:"Unable to save depot access.");}finally{setSaving("");}}

  const activeBranches=useMemo(()=>branches.filter(b=>b.active),[branches]);
  if(loading)return <main className="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8"><p className="text-sm font-bold text-slate-500">Loading depot controls…</p></main>;

  return <main className="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8">
    <header className="mb-8"><p className="text-sm font-black uppercase tracking-[0.16em] text-emerald-700">Enterprise · Multi-branch</p><h1 className="mt-2 text-3xl font-black tracking-tight">Depots & branch access</h1><p className="mt-3 max-w-3xl text-base leading-7 text-slate-600 dark:text-slate-300">Keep one company and one customer database while controlling who can work in each depot and what financial information they can see. Permissions still apply; these scopes only narrow the data each user can access.</p></header>
    {error&&<div className="mb-5 rounded-xl border border-red-200 bg-red-50 p-4 text-sm font-bold text-red-800">{error}</div>}{notice&&<div className="mb-5 rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm font-bold text-emerald-800">{notice}</div>}

    <section className="grid gap-6 xl:grid-cols-[1.1fr_.9fr]">
      <div className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-950"><div className="flex items-end justify-between gap-4"><div><h2 className="text-xl font-black">Company depots</h2><p className="mt-1 text-sm text-slate-500">The Main Depot was created automatically so existing data remains valid.</p></div><span className="rounded-full bg-emerald-50 px-3 py-1 text-xs font-black text-emerald-800">{activeBranches.length} active</span></div><div className="mt-5 grid gap-3">{branches.map(branch=><article key={branch.id} className="rounded-2xl border border-slate-200 p-4 dark:border-slate-800"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2"><h3 className="font-black">{branch.name}</h3>{branch.is_head_office&&<span className="rounded-full bg-slate-100 px-2 py-0.5 text-[10px] font-black uppercase tracking-wide text-slate-600">Head office</span>}</div><p className="mt-1 text-xs font-bold uppercase tracking-wide text-slate-400">{branch.code} · {branch.branch_type.replaceAll("_"," ")}</p>{branch.address&&<p className="mt-2 text-sm text-slate-600 dark:text-slate-300">{branch.address}</p>}</div><span className={`rounded-full px-2.5 py-1 text-xs font-black ${branch.active?"bg-emerald-50 text-emerald-800":"bg-slate-100 text-slate-500"}`}>{branch.active?"Active":"Inactive"}</span></div><div className="mt-4 flex flex-wrap items-end gap-2"><label className="min-w-56 flex-1 text-xs font-black uppercase tracking-wide text-slate-500">Depot manager<select className="mt-2 w-full rounded-lg border border-slate-300 bg-transparent px-2.5 py-2 text-sm font-semibold normal-case tracking-normal" value={branch.manager_user_id||""} onChange={e=>setBranches(current=>current.map(item=>item.id===branch.id?{...item,manager_user_id:e.target.value||null}:item))}><option value="">Not assigned</option>{members.filter(member=>["company_admin","administrator","service_manager","office"].includes(member.role)).map(member=><option key={member.userId} value={member.userId}>{member.fullName} · {member.role.replaceAll("_"," ")}</option>)}</select></label><button type="button" disabled={saving===`branch-${branch.id}`} onClick={()=>void saveBranchManager(branch.id,branch.manager_user_id||"")} className="rounded-lg border border-slate-300 px-3 py-2 text-xs font-black disabled:opacity-50">{saving===`branch-${branch.id}`?"Saving…":"Save manager"}</button></div></article>)}</div></div>

      <form onSubmit={createBranch} className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-950"><h2 className="text-xl font-black">Add depot</h2><p className="mt-1 text-sm text-slate-500">Enterprise includes the first depot. Each additional active depot adds £30/month and is synchronised to the company subscription.</p><div className="mt-5 grid gap-4"><label className="text-sm font-bold">Depot name<input className="mt-2 w-full rounded-xl border border-slate-300 bg-transparent px-3 py-2.5" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Dungannon" required/></label><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-bold">Code<input className="mt-2 w-full rounded-xl border border-slate-300 bg-transparent px-3 py-2.5" value={form.code} onChange={e=>setForm({...form,code:e.target.value})} placeholder="DGN" required/></label><label className="text-sm font-bold">Type<select className="mt-2 w-full rounded-xl border border-slate-300 bg-transparent px-3 py-2.5" value={form.branchType} onChange={e=>setForm({...form,branchType:e.target.value})}><option value="depot">Depot</option><option value="workshop">Workshop</option><option value="parts">Parts</option></select></label></div><label className="text-sm font-bold">Address<textarea className="mt-2 min-h-20 w-full rounded-xl border border-slate-300 bg-transparent px-3 py-2.5" value={form.address} onChange={e=>setForm({...form,address:e.target.value})}/></label><button disabled={saving==="new"} className="rounded-xl bg-[#103D2E] px-5 py-3 text-sm font-black text-white disabled:opacity-50">{saving==="new"?"Creating…":"Create depot"}</button></div></form>
    </section>

    <section className="mt-8 rounded-3xl border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-950"><div><h2 className="text-xl font-black">User depot & financial scopes</h2><p className="mt-1 max-w-4xl text-sm leading-6 text-slate-500">Role permissions remain authoritative. Depot scope controls operational records; finance scope independently controls whether an authorised office/manager user sees one depot, selected depots or the whole company.</p></div><div className="mt-6 overflow-x-auto"><table className="min-w-[980px] w-full text-left text-sm"><thead><tr className="border-b border-slate-200 text-xs font-black uppercase tracking-wide text-slate-500"><th className="px-3 py-3">User</th><th className="px-3 py-3">Home depot</th><th className="px-3 py-3">Operations</th><th className="px-3 py-3">Finance</th><th className="px-3 py-3">Selected depots</th><th className="px-3 py-3"></th></tr></thead><tbody className="divide-y divide-slate-100 dark:divide-slate-900">{members.map(member=><tr key={member.userId}><td className="px-3 py-4"><p className="font-black">{member.fullName}</p><p className="mt-1 text-xs text-slate-500">{member.role.replaceAll("_"," ")}</p></td><td className="px-3 py-4"><select className="rounded-lg border border-slate-300 bg-transparent px-2.5 py-2" value={member.homeBranchId||""} onChange={e=>updateMember(member.userId,{homeBranchId:e.target.value})}>{activeBranches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></td><td className="px-3 py-4"><select className="rounded-lg border border-slate-300 bg-transparent px-2.5 py-2" value={member.operationsScope} onChange={e=>updateMember(member.userId,{operationsScope:e.target.value})}>{opsOptions.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></td><td className="px-3 py-4"><select className="rounded-lg border border-slate-300 bg-transparent px-2.5 py-2" value={member.financeScope} onChange={e=>updateMember(member.userId,{financeScope:e.target.value})}>{financeOptions.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></td><td className="px-3 py-4"><div className="flex max-w-xs flex-wrap gap-2">{activeBranches.map(branch=><label key={branch.id} className="flex items-center gap-1.5 rounded-lg border border-slate-200 px-2 py-1.5 text-xs font-bold"><input type="checkbox" checked={member.branchIds.includes(branch.id)} onChange={e=>updateMember(member.userId,{branchIds:e.target.checked?[...member.branchIds,branch.id]:member.branchIds.filter(id=>id!==branch.id)})}/>{branch.code}</label>)}</div></td><td className="px-3 py-4"><button disabled={saving===member.userId} onClick={()=>void saveMember(member)} className="rounded-lg bg-slate-900 px-3 py-2 text-xs font-black text-white disabled:opacity-50">{saving===member.userId?"Saving…":"Save"}</button></td></tr>)}</tbody></table></div></section>
  </main>;
}
