
"use client";
import Link from "next/link";
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";

type Branch={id:string;code:string;name:string}; type Item={id:string;branchId:string;label:string;sub?:string};
type Payload={branches:Branch[];jobs:any[];customers:any[];machines:any[];technicians:any[];history:any[];error?:string};
const TYPES=[{id:"job",label:"Job"},{id:"customer",label:"Customer"},{id:"machine",label:"Machine"},{id:"technician",label:"Engineer"}] as const;
function related<T>(v:T|T[]|null|undefined):T|null{return !v?null:Array.isArray(v)?v[0]??null:v;}
export default function TransferCentreClient(){
 const [data,setData]=useState<Payload|null>(null),[type,setType]=useState("job"),[entityId,setEntityId]=useState(""),[toBranchId,setToBranchId]=useState(""),[reason,setReason]=useState(""),[error,setError]=useState(""),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true);
 const load=useCallback(async()=>{setLoading(true);setError("");try{const r=await fetch("/api/enterprise/transfers",{cache:"no-store"});const b=await r.json();if(!r.ok)throw new Error(b.error||"Unable to load Transfer Centre.");setData(b);}catch(e){setError(e instanceof Error?e.message:"Unable to load Transfer Centre.");}finally{setLoading(false);}},[]);useEffect(()=>{void load();},[load]);
 const items=useMemo<Item[]>(()=>{if(!data)return[];if(type==="job")return data.jobs.map(j=>{const c=related<any>(j.customers),m=related<any>(j.machines);return{id:String(j.id),branchId:String(j.branch_id??""),label:String(j.job_number||j.fault_reported||"Job"),sub:[c?.business_name||c?.contact_name,m?[m.make,m.model].filter(Boolean).join(" "):null].filter(Boolean).join(" · ")}});if(type==="customer")return data.customers.map(c=>({id:String(c.id),branchId:String(c.branch_id??""),label:String(c.business_name||c.contact_name||"Customer")}));if(type==="machine")return data.machines.map(m=>{const c=related<any>(m.customers);return{id:String(m.id),branchId:String(m.branch_id??""),label:[m.make,m.model,m.registration].filter(Boolean).join(" ")||String(m.serial_number||"Machine"),sub:c?.business_name||c?.contact_name||""}});return data.technicians.map(t=>({id:String(t.id),branchId:String(t.branchId??""),label:String(t.label),sub:String(t.role??"").replaceAll("_"," ")}));},[data,type]);
 const selected=items.find(i=>i.id===entityId); const branches=data?.branches??[]; const branchName=(id:string)=>branches.find(b=>b.id===id)?.name||"Unknown depot"; useEffect(()=>{setEntityId("");setToBranchId("");},[type]);
 async function submit(e:FormEvent){e.preventDefault();if(!selected||!toBranchId)return;setBusy(true);setError("");setNotice("");try{const r=await fetch("/api/enterprise/transfers",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({entityType:type,entityId,toBranchId,reason})});const b=await r.json();if(!r.ok)throw new Error(b.error||"Transfer failed.");setNotice(b.message||"Transfer completed.");setEntityId("");setToBranchId("");setReason("");await load();}catch(err){setError(err instanceof Error?err.message:"Transfer failed.");}finally{setBusy(false);}}
 if(loading)return <main className="mx-auto max-w-7xl p-8"><p className="font-bold text-slate-500">Loading Transfer Centre…</p></main>;
 return <main className="mx-auto max-w-7xl space-y-7 px-4 py-8 sm:px-6 lg:px-8"><header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-black uppercase tracking-[.16em] text-emerald-700">Enterprise · Cross-depot operations</p><h1 className="mt-2 text-3xl font-black">Transfer centre</h1><p className="mt-3 max-w-3xl text-slate-600 dark:text-slate-300">Move operational ownership between depots without losing history. Every transfer is written to an audit trail.</p></div><Link href="/enterprise/depots" className="rounded-xl border border-slate-300 px-4 py-3 text-sm font-black">Depot overview</Link></header>
 {error&&<div className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm font-bold text-red-800">{error}</div>}{notice&&<div className="rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm font-bold text-emerald-800">{notice}</div>}
 <section className="grid gap-6 xl:grid-cols-[.9fr_1.1fr]"><form onSubmit={submit} className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-950"><h2 className="text-xl font-black">New transfer</h2><div className="mt-5 grid gap-4"><label className="text-sm font-bold">What are you moving?<select value={type} onChange={e=>setType(e.target.value)} className="mt-2 w-full rounded-xl border border-slate-300 bg-transparent px-3 py-3">{TYPES.map(t=><option key={t.id} value={t.id}>{t.label}</option>)}</select></label><label className="text-sm font-bold">Select {TYPES.find(t=>t.id===type)?.label.toLowerCase()}<select value={entityId} onChange={e=>setEntityId(e.target.value)} className="mt-2 w-full rounded-xl border border-slate-300 bg-transparent px-3 py-3" required><option value="">Choose…</option>{items.map(i=><option key={i.id} value={i.id}>{i.label}{i.sub?` — ${i.sub}`:""} · {branchName(i.branchId)}</option>)}</select></label>{selected&&<div className="rounded-xl bg-slate-50 p-4 text-sm dark:bg-slate-900"><p className="text-xs font-black uppercase tracking-wide text-slate-500">Current depot</p><p className="mt-1 font-black">{branchName(selected.branchId)}</p></div>}<label className="text-sm font-bold">Destination depot<select value={toBranchId} onChange={e=>setToBranchId(e.target.value)} className="mt-2 w-full rounded-xl border border-slate-300 bg-transparent px-3 py-3" required><option value="">Choose…</option>{branches.filter(b=>b.id!==selected?.branchId).map(b=><option key={b.id} value={b.id}>{b.name} ({b.code})</option>)}</select></label><label className="text-sm font-bold">Reason<textarea value={reason} onChange={e=>setReason(e.target.value)} className="mt-2 min-h-24 w-full rounded-xl border border-slate-300 bg-transparent px-3 py-3" placeholder="Engineer sickness, workload balancing, customer request…"/></label><button disabled={busy||!selected||!toBranchId} className="rounded-xl bg-[#103D2E] px-5 py-3 text-sm font-black text-white disabled:opacity-50">{busy?"Transferring…":"Complete transfer"}</button></div></form>
 <div className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-950"><h2 className="text-xl font-black">Transfer rules</h2><div className="mt-4 space-y-3 text-sm leading-6 text-slate-600 dark:text-slate-300"><p><b>Jobs:</b> the working depot changes; assignments follow the job automatically.</p><p><b>Customers:</b> changes the customer's home depot only. Historic jobs and machines are not rewritten.</p><p><b>Machines:</b> changes the machine's home depot while historical jobs remain with the depot that performed them.</p><p><b>Engineers:</b> changes their home depot. Existing assignments remain intact.</p><p className="rounded-xl border border-amber-200 bg-amber-50 p-3 text-amber-900"><b>Stock transfers are intentionally not faked here.</b> Multi-depot stock needs per-depot quantity balances rather than moving the company-wide part master. That is the next inventory pack.</p></div><h3 className="mt-7 font-black">Recent transfer audit</h3><div className="mt-3 space-y-2">{(data?.history??[]).length===0?<p className="text-sm text-slate-500">No transfers yet.</p>:(data?.history??[]).map(h=><div key={h.id} className="rounded-xl bg-slate-50 px-4 py-3 text-sm dark:bg-slate-900"><div className="flex justify-between gap-3"><p className="font-black">{h.entity_label||h.entity_type}</p><span className="text-xs font-bold uppercase text-emerald-700">{h.status}</span></div><p className="mt-1 text-xs text-slate-500">{branchName(String(h.from_branch_id))} → {branchName(String(h.to_branch_id))} · {new Date(h.requested_at).toLocaleString()}</p>{h.reason&&<p className="mt-1 text-xs text-slate-600">{h.reason}</p>}</div>)}</div></div></section></main>;
}
