"use client";
import {useEffect,useState} from "react";import Link from "next/link";
export default function NetworkProvidersAdmin(){const[data,setData]=useState<any>({providers:[],reports:[]}),[error,setError]=useState("");
 async function load(){const r=await fetch("/api/platform/network-providers",{cache:"no-store"});const b=await r.json();if(!r.ok)setError(b.error||"Unable to load.");else setData(b)}
 useEffect(()=>{void load()},[]);
 async function act(payload:any){const r=await fetch("/api/platform/network-providers",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const b=await r.json();if(!r.ok){setError(b.error||"Unable to save.");return;}void load()}
 return <main className="min-h-dvh bg-slate-50 p-4 sm:p-6 lg:p-8 dark:bg-slate-950"><div className="mx-auto max-w-7xl space-y-6"><header className="flex flex-wrap justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-[.16em] text-emerald-700">AgriCore Platform</p><h1 className="mt-1 text-3xl font-black">Network provider approval</h1><p className="mt-2 text-sm text-slate-500">Subscription does not equal marketplace approval. Review every provider before public listing.</p></div><Link href="/platform" className="rounded-xl border px-4 py-2 font-bold">Platform home</Link></header>{error?<p className="rounded-xl bg-red-50 p-3 text-red-700">{error}</p>:null}
 <section className="space-y-4">{data.providers.map((p:any)=>{const c=p.companies;return <article key={p.id} className="rounded-3xl border bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><div className="flex flex-wrap justify-between gap-4"><div><h2 className="text-xl font-black">{p.display_name}</h2><p className="mt-1 text-sm text-slate-500">{c?.company_name} · {c?.billing_mode} · {p.town_city||"No location"} · status <b>{p.approval_status}</b></p><p className="mt-3 max-w-3xl text-sm">{p.description}</p></div><div className="flex flex-wrap items-start gap-2">{p.approval_status!=="approved"?<button onClick={()=>act({action:"approve",profile_id:p.id})} className="rounded-xl bg-emerald-700 px-4 py-2 text-sm font-black text-white">Approve</button>:null}<button onClick={()=>act({action:"suspend",profile_id:p.id,reason:"Suspended pending review"})} className="rounded-xl border border-red-200 px-4 py-2 text-sm font-black text-red-700">Suspend</button><button onClick={()=>act({action:"reject",profile_id:p.id})} className="rounded-xl border px-4 py-2 text-sm font-black">Reject</button></div></div><div className="mt-4 flex flex-wrap gap-3 text-sm">{["business","identity","insurance"].map(k=><button key={k} onClick={()=>act({action:k,profile_id:p.id,value:"verified"})} className={`rounded-full px-3 py-1.5 font-bold ${p[`${k}_verification`]==="verified"?"bg-emerald-100 text-emerald-800":"bg-slate-100"}`}>{k}: {p[`${k}_verification`]}</button>)}</div><p className="mt-4 text-xs text-slate-500">Brands: {(p.brands??[]).join(", ")||"—"} · Services: {(p.services??[]).join(", ")||"—"} · Notes: {p.application_notes||"—"}</p></article>})}</section>
 <section className="rounded-3xl border bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><h2 className="text-xl font-black">Open provider reports</h2><div className="mt-4 space-y-3">{data.reports.length?data.reports.map((r:any)=><div key={r.id} className="rounded-xl border p-4"><p className="font-black">{r.reason}</p><p className="mt-1 text-sm text-slate-500">{r.detail||"No further detail"}</p><button onClick={()=>act({action:"resolve_report",profile_id:r.provider_profile_id,report_id:r.id})} className="mt-3 rounded-lg border px-3 py-1.5 text-xs font-black">Resolve</button></div>):<p className="text-sm text-slate-500">No open reports.</p>}</div></section>
 </div></main>}