import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, BarChart3, CalendarDays, Camera, CheckCircle2, ClipboardCheck, CloudOff, FileSignature, FileText, MapPin, PackageSearch, ShoppingCart, Smartphone, Tractor, Users, Wrench } from "lucide-react";
import MarketingShell from "@/Components/marketing/marketing-shell";

export const metadata: Metadata = { title: "Features", description: "Explore AgriCore features for agricultural engineering workshops, machinery service teams and field engineers." };

const groups = [
  { title: "Run the office", copy:"Give the office one operational view of customers, machines and work.", items: [[Users,"Customers","Keep contact details, sites, notes, jobs, quotes, invoices and machine relationships organised."],[Tractor,"Machines","Build a permanent machine record with serial numbers, hours, service programmes and repair history."],[CalendarDays,"Calendar & dispatch","Schedule work, see workload and coordinate technicians across the day or week."],[FileText,"Quotes & invoices","Create professional documents from the same job information instead of retyping it."]] },
  { title: "Work in the field", copy:"Give technicians a focused mobile workflow instead of an office system squeezed onto a phone.", items: [[Smartphone,"Technician Pro","Travel, labour, parts, machine details and next actions in one field-friendly view."],[CloudOff,"Offline-ready working","Queue key field updates and use the Sync Centre when rural signal disappears."],[Camera,"Job photos","Attach evidence, faults, repairs and completed work directly to the job."],[FileSignature,"Digital signatures","Capture customer sign-off against completed work without paper forms."]] },
  { title: "Control service & stock", copy:"Keep planned service, parts and purchasing connected to the work being done.", items: [[ClipboardCheck,"Service programmes","Create repeatable maintenance schedules and surface upcoming service work."],[PackageSearch,"Stock control","Track quantities, cost, retail value, low-stock alerts and movement history."],[ShoppingCart,"Purchase orders","Create supplier orders, receive deliveries and update linked stock automatically."],[MapPin,"GPS & travel","Support field visibility, travel status and return-journey records where enabled."]] },
  { title: "Understand the business", copy:"Turn operational records into useful management information.", items: [[BarChart3,"Reports Centre","Review revenue, invoice ageing, labour, jobs, customers, service exposure and stock."],[Wrench,"Job history","Keep labour, parts, notes, checklists, photos and completion data attached to each job."],[Users,"Company roles","Control financial, operational and administrative access by company role."],[CheckCircle2,"Company isolation","Each business operates within its own company workspace and data scope."]] },
];

export default function FeaturesPage() { return <MarketingShell><main><section className="mx-auto max-w-7xl px-5 py-16 sm:px-8 lg:px-10 lg:py-24"><div className="max-w-4xl"><p className="text-sm font-black uppercase tracking-[0.18em] text-emerald-700">AgriCore features</p><h1 className="mt-4 text-5xl font-black tracking-[-0.05em] sm:text-6xl">Built around agricultural service work—not adapted to it.</h1><p className="mt-6 max-w-3xl text-lg font-medium leading-8 text-slate-600 dark:text-slate-300">From the first customer call through machine history, scheduling, field work, stock, completion and invoicing, AgriCore keeps the information together.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href="/signup" className="inline-flex items-center justify-center gap-2 rounded-2xl bg-emerald-700 px-6 py-4 font-black text-white">Start free trial <ArrowRight className="h-5 w-5"/></Link><Link href="/demo" className="inline-flex items-center justify-center rounded-2xl border border-emerald-950/10 bg-white px-6 py-4 font-black dark:border-white/10 dark:bg-white/5">See product demo</Link></div></div></section>{groups.map((group, groupIndex)=><section key={group.title} className={groupIndex % 2 ? "border-y border-emerald-950/10 bg-white/60 dark:border-white/10 dark:bg-white/[0.03]" : ""}><div className="mx-auto max-w-7xl px-5 py-16 sm:px-8 lg:px-10"><p className="text-sm font-black uppercase tracking-[0.16em] text-emerald-700">0{groupIndex+1}</p><h2 className="mt-2 text-3xl font-black tracking-tight">{group.title}</h2><p className="mt-3 max-w-2xl text-base font-medium leading-7 text-slate-600 dark:text-slate-300">{group.copy}</p><div className="mt-8 grid gap-4 md:grid-cols-2 lg:grid-cols-4">{group.items.map(([Icon,title,copy])=>{const I=Icon as typeof Users;return <article key={String(title)} className="rounded-3xl border border-emerald-950/10 bg-white p-6 shadow-sm dark:border-white/10 dark:bg-slate-900"><I className="h-7 w-7 text-emerald-700"/><h3 className="mt-5 text-lg font-black">{String(title)}</h3><p className="mt-2 text-sm font-medium leading-6 text-slate-600 dark:text-slate-300">{String(copy)}</p></article>})}</div></div></section>)}<section className="mx-auto max-w-7xl px-5 py-20 sm:px-8 lg:px-10"><div className="rounded-[2rem] bg-emerald-950 p-8 text-white sm:p-12"><CheckCircle2 className="h-8 w-8 text-emerald-300"/><h2 className="mt-5 text-4xl font-black">See it on your own workflow.</h2><p className="mt-4 max-w-2xl text-base font-medium leading-7 text-emerald-50/80">Start a 14-day AgriCore trial on the plan that fits your business and set it up around your customers, machines and technicians.</p><Link href="/signup" className="mt-7 inline-flex items-center gap-2 rounded-2xl bg-white px-5 py-3.5 font-black text-emerald-950">Start free trial <ArrowRight className="h-5 w-5"/></Link></div></section></main></MarketingShell> }
