import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, CalendarDays, Camera, CheckCircle2, ClipboardCheck, CloudOff, FileSignature, FileText, MapPin, PackageSearch, Smartphone, Tractor, Users, Wrench } from "lucide-react";
import MarketingShell from "@/Components/marketing/marketing-shell";

export const metadata: Metadata = { title: "Features", description: "Explore AgriCore features for agricultural engineering workshops and field-service teams." };

const groups = [
  { title: "Run the office", items: [[Users,"Customers","Keep customer details and service relationships organised."],[Tractor,"Machines","Build a permanent machine record with service and job history."],[CalendarDays,"Calendar & dispatch","Schedule work and coordinate technicians across the week."],[FileText,"Quotes & invoices","Create professional documents from the same job information."]] },
  { title: "Work in the field", items: [[Smartphone,"Technician mobile workflow","A focused view designed for engineers working from a phone."],[CloudOff,"Offline-ready working","Keep key field workflows available when rural signal is poor."],[Camera,"Job photos","Attach evidence, faults, repairs and completed work to the job."],[FileSignature,"Digital signatures","Capture customer sign-off directly against completed work."]] },
  { title: "Build repeatable service", items: [[ClipboardCheck,"Service programmes","Create planned maintenance routines for machines and fleets."],[Wrench,"Job history","Keep labour, parts, notes and completion data attached to each job."],[PackageSearch,"Stock","Record stock and parts used against work."],[MapPin,"GPS & travel","Support field visibility and travel-related job records."]] },
];

export default function FeaturesPage() { return <MarketingShell><main><section className="mx-auto max-w-7xl px-5 py-16 sm:px-8 lg:px-10 lg:py-24"><div className="max-w-4xl"><p className="text-sm font-black uppercase tracking-[0.18em] text-emerald-700">AgriCore features</p><h1 className="mt-4 text-5xl font-black tracking-[-0.05em] sm:text-6xl">Built around agricultural service work—not adapted to it.</h1><p className="mt-6 max-w-3xl text-lg font-medium leading-8 text-slate-600 dark:text-slate-300">From the first customer call through machine history, scheduling, field work, completion and invoicing, AgriCore keeps the information together.</p></div></section>{groups.map((group, groupIndex)=><section key={group.title} className={groupIndex % 2 ? "border-y border-emerald-950/10 bg-white/60 dark:border-white/10 dark:bg-white/[0.03]" : ""}><div className="mx-auto max-w-7xl px-5 py-16 sm:px-8 lg:px-10"><h2 className="text-3xl font-black tracking-tight">{group.title}</h2><div className="mt-8 grid gap-4 md:grid-cols-2 lg:grid-cols-4">{group.items.map(([Icon,title,copy])=>{const I=Icon as typeof Users;return <article key={String(title)} className="rounded-3xl border border-emerald-950/10 bg-white p-6 shadow-sm dark:border-white/10 dark:bg-slate-900"><I className="h-7 w-7 text-emerald-700"/><h3 className="mt-5 text-lg font-black">{String(title)}</h3><p className="mt-2 text-sm font-medium leading-6 text-slate-600 dark:text-slate-300">{String(copy)}</p></article>})}</div></div></section>)}<section className="mx-auto max-w-7xl px-5 py-20 sm:px-8 lg:px-10"><div className="rounded-[2rem] bg-emerald-950 p-8 text-white sm:p-12"><CheckCircle2 className="h-8 w-8 text-emerald-300"/><h2 className="mt-5 text-4xl font-black">See it on your own workflow.</h2><p className="mt-4 max-w-2xl text-base font-medium leading-7 text-emerald-50/80">Start a 14-day trial and set AgriCore up around your customers, machines and technicians.</p><Link href="/signup" className="mt-7 inline-flex items-center gap-2 rounded-2xl bg-white px-5 py-3.5 font-black text-emerald-950">Start free trial <ArrowRight className="h-5 w-5"/></Link></div></section></main></MarketingShell> }
