"use client";
import { FormEvent, Suspense, useEffect, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import AgriCoreMark from "@/Components/branding/agricore-mark";
import { supabase } from "@/lib/supabase";
function safe(v:string|null){return v?.startsWith("/")&&!v.startsWith("//")?v:"/dashboard"}
function Challenge(){const router=useRouter(),params=useSearchParams(),redirectTo=safe(params.get("redirectTo"));const[factors,setFactors]=useState<Array<{id:string;friendly_name?:string|null}>>([]),[factorId,setFactorId]=useState(""),[code,setCode]=useState(""),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState("");
useEffect(()=>{void(async()=>{try{const aal=await supabase.auth.mfa.getAuthenticatorAssuranceLevel();if(aal.error)throw aal.error;if(aal.data.currentLevel==="aal2"){router.replace(redirectTo);return}const listed=await supabase.auth.mfa.listFactors();if(listed.error)throw listed.error;const verified=(listed.data.totp??[]).filter(f=>f.status==="verified");if(!verified.length){router.replace(`/mfa/setup?redirectTo=${encodeURIComponent(redirectTo)}`);return}setFactors(verified);setFactorId(verified[0].id)}catch(e){setError(e instanceof Error?e.message:"Unable to load two-factor authentication.")}finally{setLoading(false)}})()},[redirectTo,router]);
async function verify(e:FormEvent){e.preventDefault();if(!/^\d{6}$/.test(code))return setError("Enter the 6-digit code from your authenticator.");setSaving(true);setError("");try{const r=await supabase.auth.mfa.challengeAndVerify({factorId,code});if(r.error)throw r.error;router.replace(redirectTo);router.refresh()}catch(err){setError(err instanceof Error?err.message:"Code not accepted.")}finally{setSaving(false)}}
return <main className="flex min-h-dvh items-center justify-center bg-slate-50 px-4 dark:bg-slate-950"><div className="w-full max-w-md rounded-3xl border bg-white p-8 shadow-xl dark:border-slate-800 dark:bg-slate-900"><div className="flex items-center gap-3"><AgriCoreMark size={54}/><b className="text-emerald-700">AgriCore Security</b></div><h1 className="mt-6 text-3xl font-black">Enter your 6-digit code</h1><p className="mt-2 text-sm text-slate-500">Open Apple Passwords or your authenticator app and enter the current verification code.</p>{loading?<p className="mt-6 text-sm">Loading…</p>:<form onSubmit={verify} className="mt-7 space-y-5">{factors.length>1?<select value={factorId} onChange={e=>setFactorId(e.target.value)} className="w-full rounded-xl border px-4 py-3">{factors.map((f,i)=><option key={f.id} value={f.id}>{f.friendly_name||`Authenticator ${i+1}`}</option>)}</select>:null}<input autoFocus inputMode="numeric" autoComplete="one-time-code" maxLength={6} value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,"").slice(0,6))} placeholder="123456" className="w-full rounded-xl border px-4 py-4 text-center font-mono text-3xl tracking-[.3em] dark:bg-slate-950"/>{error?<div className="rounded-xl bg-red-50 p-3 text-sm font-semibold text-red-700">{error}</div>:null}<button disabled={saving||code.length!==6} className="w-full rounded-xl bg-emerald-700 px-4 py-3.5 font-black text-white disabled:opacity-50">{saving?"Verifying…":"Verify & continue"}</button></form>}</div></main>}
export default function MfaPage(){return <Suspense><Challenge/></Suspense>}
